[package]
name = "pdf-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lopdf = { version = "0.32", default-features = false, features = ["pom_parser"] }
pdf-writer = "0.10"
